# Generated by Django 4.0.3 on 2022-03-26 23:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='another_invite_code',
            field=models.CharField(blank=True, max_length=6, verbose_name='Введите чужой инвайт код, если он у вас есть'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='auth_code',
            field=models.IntegerField(default=6125, unique=True, verbose_name='Код для авторизации'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='invited_users',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Приглашенные вами пользователи'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='invite_code',
            field=models.CharField(blank=True, max_length=6, verbose_name='Твой собственный инвайт-код'),
        ),
    ]
