# Generated by Django 4.0.3 on 2022-03-26 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='another_invite_code',
            field=models.CharField(blank=True, max_length=6, verbose_name='Чужой инвайт-код'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='invite_code',
            field=models.CharField(blank=True, max_length=6, verbose_name='Твой собственный инвайт-код'),
        ),
    ]
