# Generated by Django 4.0.3 on 2022-03-26 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_customuser_another_invite_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='another_invite_code',
            field=models.CharField(blank=True, max_length=6, verbose_name='Введите чужой инвайт код, если он у вас есть'),
        ),
    ]
