# Generated by Django 4.0.3 on 2022-03-27 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_customuser_another_invite_code_customuser_auth_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='auth_code',
            field=models.IntegerField(default=1851, unique=True, verbose_name='Код для авторизации'),
        ),
    ]
