# Generated by Django 4.0.3 on 2022-03-26 11:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_customuser_another_invite_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='invited_users',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Приглашенные вами пользователи'),
        ),
    ]
