# Generated by Django 4.0.3 on 2022-03-27 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_customuser_auth_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='invited_users',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='auth_code',
            field=models.IntegerField(default=1426, unique=True, verbose_name='Код для авторизации'),
        ),
        migrations.CreateModel(
            name='RelatedUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invited_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь, которого пригласили')),
                ('inviter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь, который пригласил')),
            ],
            options={
                'verbose_name': 'Связанный пользователь',
                'verbose_name_plural': 'Связанные пользователи',
            },
        ),
    ]
