# Generated by Django 4.0.3 on 2022-03-26 13:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_customuser_invited_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='invited_users',
        ),
        migrations.AddField(
            model_name='customuser',
            name='invited_users',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL, verbose_name='Приглашенные вами пользователи'),
        ),
    ]
