# Generated by Django 4.0.3 on 2022-03-26 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_customuser_invited_users_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='invited_users',
        ),
        migrations.AddField(
            model_name='customuser',
            name='invited_users',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Приглашенные вами пользователи'),
        ),
    ]
