# Generated by Django 4.0.3 on 2022-03-27 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_customuser_invited_users_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='auth_code',
            field=models.IntegerField(default=8748, unique=True, verbose_name='Код для авторизации'),
        ),
        migrations.AlterField(
            model_name='relatedusers',
            name='invited_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users_invited', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь, которого пригласили'),
        ),
        migrations.AlterField(
            model_name='relatedusers',
            name='inviter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users_inviters', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь, который пригласил'),
        ),
    ]
